//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class test1Entities : DbContext
    {
        public test1Entities()
            : base("name=test1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ces> ces { get; set; }
        public virtual DbSet<table1> table1 { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<b> b { get; set; }
        public virtual DbSet<package> package { get; set; }
        public virtual DbSet<v_view> v_view { get; set; }
    }
}
